#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Yuuki Ishizaka
# SPDX-License-Identifier: BSD-3-Clause

import sys

def get_eto(year):
    eto_list = ["申", "酉", "戌", "亥", "子", "丑", "寅", "卯", "辰", "巳", "午", "未"]
    eto_index = year % 12
    return eto_list[eto_index]

if __name__ == "__main__":
    input_data = sys.stdin.read().strip()
    try:
        year = int(input_data)
        eto = get_eto(year)
        print(f"{year} 年の干支は{eto}です。")
    except ValueError:
        sys.exit(1)

